### ISSUE TITLE
Pruebas en CFDI 4.0

### ISSUE THREAD

**Issue by eclipxe13** [phpcfdi/finkok#30]
La librería tiene las pruebas basadas en CFDI 3.3.
Es necesario cambiar a CFDI 4.0 debido a que a partir de 2023-01-01 la versión 3.3 dejará de ser válida y las pruebas inevitablemente comenzarán a fallar.

**Comment by AndreyPootMay** [comment]
Me lo asigno

**Comment by eclipxe13** [comment]
Cerrado en #32
