### ISSUE TITLE
CancelSignatureService: xml cambio de formato

### ISSUE THREAD

**Issue by rafaelhecr** [phpcfdi/finkok#36]
En la wiki de Finkok, en la parte de Cancel_Signature: https://wiki.finkok.com/doku.php?id=cancelsigned_method menciona que el XML que se envia por este método tiene cambios: https://wiki.finkok.com/doku.php?id=cancel_signature2022.

El cambio mas relevante: 
<img width="1236" alt="Captura de Pantalla 2022-08-17 a la(s) 21 29 19" src="https://user-images.githubusercontent.com/19279811/185279579-b3005c28-d517-44d6-9283-e2439136bade.png">

**Comment by eclipxe13** [comment]
Así es, y el cambio está implementado desde la versión 0.4.0.

Esta librería depende de phpcfdi/xml-cancelacion donde se genera el XML y
se firma. Luego se envía a Finkok usando el método que recibe la
cancelación firmada.

**Comment by rafaelhecr** [comment]
Cierto! Disculpa, ya pude hacer funcionar el código!.
